### ISSUE TITLE
Move hyperstart mock object to virtcontainers

### ISSUE THREAD

**Issue by dlespiau** [sameo/virtcontainers#40]
The plan is to put the low level interface to hyperstart into virtcontainers and have the runtime depend on it. I think it'd be only natural to put the object mocking hyperstart (for testing purposes) into virtcontainers as well.

The package name could be vircontainers/hyperstart/mock.

That will also avoid having an unpleasant circular dependency between the OCI runtime and virtcontainers repositories.

**Comment by sameo** [comment]
Fixed with commit f490c536e51584683085c0360f081af2bb6bea52
